//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoCuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int MaAD { get; set; }
        public string TenAD { get; set; }
        public string DiaChiAD { get; set; }
        public string SDTAdmin { get; set; }
        public string TenDNAD { get; set; }
        public string MatKhauAD { get; set; }
        public string EmailAD { get; set; }
        public string Vaitro { get; set; }
        public string AVT { get; set; }
    }
}
