//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDoCuoi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public int STT { get; set; }
        public int MaSP { get; set; }
        public string Anh1 { get; set; }
        public string Anh2 { get; set; }
        public string Anh3 { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
